In [17]:
import pandas as pd

In [20]:
df = pd.read_csv("ventas_historicas.csv")

In [21]:
df.shape

(300, 10)

In [22]:
df.dtypes

id_venta         int64
mes                str
region             str
vendedor           str
categoria          str
canal              str
cantidad         int64
precio_unit    float64
descuento      float64
monto_bruto    float64
dtype: object

In [23]:
df.head()

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
1,1002,Enero,Oeste,Carlos Rivas,Laptop,Online,4,894.32,0.0,3577.28
2,1003,Abril,Oeste,Laura Diaz,Tablet,Online,13,375.14,15.0,4876.82
3,1004,Enero,Este,Camila Vega,Laptop,Online,6,1010.65,NaN,6063.90
4,1005,Enero,Norte,Laura Diaz,Teclado,NaN,10,78.27,0.0,782.70

In [24]:
df.isnull()

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
295,False,False,False,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False

In [25]:
df.sum()

id_venta                                                  345150
mes            JunioEneroAbrilEneroEneroEneroJunioJunioMarzoM...
region         NorteOesteOesteEsteNorteSurEsteCentroCentroCen...
vendedor       Laura DiazCarlos RivasLaura DiazCamila VegaLau...
categoria      LaptopLaptopTabletLaptopTecladoMonitorAuricula...
canal          OnlineOnlineOnlineOnlineOnlineMayoristaOnlineM...
cantidad                                                    2398
precio_unit                                             87016.77
descuento                                                 2000.0
monto_bruto                                            729325.92
dtype: object

In [26]:
filtro = df[(df['region'] == 'Centro') & (df['monto_bruto'] > 300)]

In [27]:
filtro

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
7,1008,Junio,Centro,Javier Munoz,Tablet,Online,4,377.19,20.0,1508.76
8,1009,Marzo,Centro,Pedro Soto,Auriculares,Mayorista,8,120.99,15.0,967.92
11,1012,Junio,Centro,Carlos Rivas,Laptop,Mayorista,15,905.07,0.0,13576.05
13,1014,Febrero,Centro,Javier Munoz,Tablet,Online,9,394.05,10.0,3546.45
15,1016,Febrero,Centro,Roberto Fuentes,Tablet,Mayorista,3,305.93,20.0,917.79
24,1025,Junio,Centro,Roberto Fuentes,Auriculares,Online,4,116.24,0.0,464.96
30,1031,Junio,Centro,Laura Diaz,Laptop,Mayorista,2,1041.74,0.0,2083.48
43,1044,Junio,Centro,Camila Vega,Monitor,Tienda fisica,7,327.38,10.0,2291.66
50,1051,Mayo,Centro,Javier Munoz,Mouse,Tienda fisica,10,41.16,10.0,411.60
69,1070,Abril,Centro,Javier Munoz,Monitor,Tienda fisica,12,310.35,0.0,3724.20
79,1080,Febrero,Centro,Camila Vega,Auriculares,Online,9,112.79,0.0,1015.11
87,1088,Junio,Centro,Maria Lopez,Tablet,Tienda fisica,9,273.75,5.0,2463.75
95,1096,Abril,Centro,Carlos Rivas,Auriculares,Tienda fisica,14,134.37,10.0,1881.18
108,1109,Junio,Centro,Javier Munoz,Teclado,Online,11,61.33,0.0,674.63
109,1110,Junio,Centro,Carlos Rivas,Tablet,Mayorista,14,331.43,15.0,4640.02
111,1112,Mayo,Centro,Maria Lopez,Teclado,Tienda fisica,11,57.82,5.0,636.02
120,1121,Junio,Centro,Javier Munoz,Mouse,Tienda fisica,10,37.18,5.0,371.80
126,1127,Enero,Centro,Laura Diaz,Monitor,Mayorista,4,340.14,20.0,1360.56
127,1128,Mayo,Centro,Laura Diaz,Laptop,NaN,3,815.41,20.0,2446.23
130,1131,Junio,Centro,Carlos Rivas,Laptop,Tienda fisica,8,947.56,5.0,7580.48
131,1132,Marzo,Centro,Camila Vega,Laptop,NaN,5,953.09,10.0,4765.45
142,1143,Abril,Centro,Roberto Fuentes,Mouse,Mayorista,9,43.11,15.0,387.99
148,1149,Junio,Centro,Camila Vega,Laptop,Mayorista,6,728.70,0.0,4372.20
150,1151,Junio,Centro,Javier Munoz,Laptop,Mayorista,3,925.56,0.0,2776.68
158,1159,Enero,Centro,Ana Torres,Laptop,Tienda fisica,4,1006.39,10.0,4025.56
179,1180,Mayo,Centro,NaN,Auriculares,Online,7,126.14,20.0,882.98
185,1186,Marzo,Centro,Javier Munoz,Tablet,Mayorista,14,316.21,5.0,4426.94
191,1192,Mayo,Centro,Carlos Rivas,Monitor,Online,2,292.19,20.0,584.38
194,1195,Mayo,Centro,NaN,Monitor,Mayorista,10,281.28,20.0,2812.80
200,1201,Febrero,Centro,Pedro Soto,Teclado,Tienda fisica,9,63.01,0.0,567.09
204,1205,Junio,Centro,Pedro Soto,Tablet,Online,2,324.90,15.0,649.80
205,1206,Abril,Centro,Roberto Fuentes,Tablet,Tienda fisica,11,297.53,0.0,3272.83
208,1209,Enero,Centro,Javier Munoz,Mouse,Tienda fisica,8,43.60,10.0,348.80
209,1210,Marzo,Centro,Pedro Soto,Teclado,NaN,6,59.47,5.0,356.82
231,1232,Junio,Centro,Pedro Soto,Auriculares,Tienda fisica,4,143.73,0.0,574.92
237,1238,Enero,Centro,NaN,Auriculares,Online,14,134.07,20.0,1876.98
244,1245,Marzo,Centro,Ana Torres,Teclado,Online,11,79.32,NaN,872.52
256,1257,Marzo,Centro,Javier Munoz,Tablet,Mayorista,12,297.71,0.0,3572.52
258,1259,Junio,Centro,Ana Torres,Tablet,Mayorista,8,392.70,0.0,3141.60
265,1266,Marzo,Centro,Roberto Fuentes,Teclado,Online,8,74.02,5.0,592.16
267,1268,Abril,Centro,Pedro Soto,Teclado,Tienda fisica,11,60.05,15.0,660.55
269,1270,Mayo,Centro,Maria Lopez,Laptop,Tienda fisica,6,789.51,0.0,4737.06
272,1273,Abril,Centro,Maria Lopez,Teclado,Mayorista,7,66.25,5.0,463.75
277,1278,Junio,Centro,Roberto Fuentes,Laptop,Mayorista,4,1059.02,0.0,4236.08
279,1280,Marzo,Centro,Camila Vega,Auriculares,Online,10,108.68,0.0,1086.80
280,1281,Mayo,Centro,Maria Lopez,Monitor,Tienda fisica,12,280.45,10.0,3365.40
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18

In [28]:
filtro1 = df[(df['canal'] == 'Online') & (df['descuento'] >= 15)]

In [29]:
filtro1.loc[:, ['region', 'categoria', 'cantidad', 'monto_bruto', 'descuento']]

     region    categoria  cantidad  monto_bruto  descuento
2     Oeste       Tablet        13      4876.82       15.0
5       Sur      Monitor         7      1951.18       15.0
7    Centro       Tablet         4      1508.76       20.0
20    Norte  Auriculares         7       958.65       20.0
23    Oeste       Laptop         7      5688.69       20.0
36      Sur       Tablet        12      4683.96       20.0
48    Oeste      Teclado        11       804.43       20.0
49      Sur       Tablet         9      2735.10       20.0
60    Oeste  Auriculares        10      1311.50       15.0
70    Norte  Auriculares        12      1532.64       20.0
90    Oeste      Monitor         5      1653.60       20.0
112    Este       Tablet        14      4457.88       15.0
132   Oeste        Mouse         5       214.90       20.0
133   Norte      Teclado         3       195.42       15.0
149   Oeste       Tablet         2       619.72       20.0
159    Este       Tablet         4      1302.96       20.0
179  Centro  Auriculares         7       882.98       20.0
191  Centro      Monitor         2       584.38       20.0
204  Centro       Tablet         2       649.80       15.0
228    Este  Auriculares         5       600.35       20.0
237  Centro  Auriculares        14      1876.98       20.0
282     Sur  Auriculares        10      1323.60       15.0
289     Sur        Mouse         1        39.49       20.0
297  Centro       Laptop         1      1036.18       20.0

In [30]:
filtro2 = df[df['categoria'].isin(['Laptop', 'Tablet'])]

In [31]:
filtro2

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
1,1002,Enero,Oeste,Carlos Rivas,Laptop,Online,4,894.32,0.0,3577.28
2,1003,Abril,Oeste,Laura Diaz,Tablet,Online,13,375.14,15.0,4876.82
3,1004,Enero,Este,Camila Vega,Laptop,Online,6,1010.65,NaN,6063.90
7,1008,Junio,Centro,Javier Munoz,Tablet,Online,4,377.19,20.0,1508.76
...,...,...,...,...,...,...,...,...,...,...
287,1288,Marzo,Este,Carlos Rivas,Tablet,Mayorista,6,304.05,0.0,1824.30
290,1291,Febrero,Oeste,Camila Vega,Laptop,Online,12,996.53,0.0,11958.36
296,1297,Abril,Este,Camila Vega,Tablet,Tienda fisica,9,359.42,20.0,3234.78
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18
299,1300,Mayo,Sur,Javier Munoz,Tablet,Tienda fisica,10,353.19,20.0,3531.90

In [32]:
filtro2.shape

(97, 10)

In [33]:
# tiene 97 filas

In [34]:
filtro3 = df[df['cantidad'].between(8, 15)]

In [35]:
filtro3

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
2,1003,Abril,Oeste,Laura Diaz,Tablet,Online,13,375.14,15.0,4876.82
4,1005,Enero,Norte,Laura Diaz,Teclado,NaN,10,78.27,0.0,782.70
6,1007,Junio,Este,Carlos Rivas,Auriculares,Mayorista,11,110.21,15.0,1212.31
8,1009,Marzo,Centro,Pedro Soto,Auriculares,Mayorista,8,120.99,15.0,967.92
11,1012,Junio,Centro,Carlos Rivas,Laptop,Mayorista,15,905.07,0.0,13576.05
...,...,...,...,...,...,...,...,...,...,...
294,1295,Marzo,Norte,Pedro Soto,Auriculares,Mayorista,10,126.46,15.0,1264.60
295,1296,Abril,Sur,Carlos Rivas,Teclado,Online,8,71.84,0.0,574.72
296,1297,Abril,Este,Camila Vega,Tablet,Tienda fisica,9,359.42,20.0,3234.78
298,1299,Junio,Oeste,Camila Vega,Teclado,Online,11,69.20,10.0,761.20
299,1300,Mayo,Sur,Javier Munoz,Tablet,Tienda fisica,10,353.19,20.0,3531.90

In [36]:
"""
se usa & y | porque and y or son palabras reservadas de python

.isin() es mas conveniente de usar ya que analiza todo el DF
"""

'\nse usa & y | porque and y or son palabras reservadas de python\n\n.isin() es mas conveniente de usar ya que analiza todo el DF\n'

In [37]:
filtro4 = df[((df['mes'].isin(['Enero', 'Febrero'])) & 
              (df['categoria'].isin(['Laptop', 'Tablet']))) & 
              (df['descuento'] >= 10)]

In [38]:
filtro4

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
13,1014,Febrero,Centro,Javier Munoz,Tablet,Online,9,394.05,10.0,3546.45
15,1016,Febrero,Centro,Roberto Fuentes,Tablet,Mayorista,3,305.93,20.0,917.79
23,1024,Febrero,Oeste,Camila Vega,Laptop,Online,7,812.67,20.0,5688.69
149,1150,Febrero,Oeste,Maria Lopez,Tablet,Online,2,309.86,20.0,619.72
157,1158,Febrero,Este,Ana Torres,Tablet,Tienda fisica,15,378.21,15.0,5673.15
158,1159,Enero,Centro,Ana Torres,Laptop,Tienda fisica,4,1006.39,10.0,4025.56
187,1188,Febrero,Oeste,Javier Munoz,Tablet,Mayorista,12,312.03,20.0,3744.36
247,1248,Enero,Este,Camila Vega,Laptop,Online,14,748.35,10.0,10476.90
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18

In [39]:
 filtro4.nlargest(5,'monto_bruto')

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
247,1248,Enero,Este,Camila Vega,Laptop,Online,14,748.35,10.0,10476.90
23,1024,Febrero,Oeste,Camila Vega,Laptop,Online,7,812.67,20.0,5688.69
157,1158,Febrero,Este,Ana Torres,Tablet,Tienda fisica,15,378.21,15.0,5673.15
158,1159,Enero,Centro,Ana Torres,Laptop,Tienda fisica,4,1006.39,10.0,4025.56
187,1188,Febrero,Oeste,Javier Munoz,Tablet,Mayorista,12,312.03,20.0,3744.36

In [40]:
filtro5 = df[(df['region'].isin(['Norte', 'Sur'])) & 
             (df['monto_bruto'] >= df['monto_bruto'].mean()) & 
             (df['cantidad'] >= 10)]

print(df['monto_bruto'].mean())

2431.0863999999997

In [41]:
filtro5

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
25,1026,Mayo,Norte,NaN,Laptop,Mayorista,15,1012.42,0.0,15186.30
36,1037,Abril,Sur,Ana Torres,Tablet,Online,12,390.33,20.0,4683.96
37,1038,Febrero,Sur,Carlos Rivas,Monitor,Tienda fisica,14,250.99,5.0,3513.86
42,1043,Abril,Sur,Carlos Rivas,Monitor,Mayorista,15,284.80,0.0,4272.00
46,1047,Mayo,Norte,Javier Munoz,Monitor,Online,14,356.93,0.0,4997.02
47,1048,Febrero,Norte,Roberto Fuentes,Laptop,Mayorista,14,983.79,5.0,13773.06
59,1060,Febrero,Norte,Pedro Soto,Laptop,Online,10,774.31,0.0,7743.10
62,1063,Junio,Sur,Laura Diaz,Laptop,Mayorista,10,996.38,20.0,9963.80
75,1076,Mayo,Sur,Camila Vega,Laptop,Mayorista,10,991.35,0.0,9913.50
114,1115,Marzo,Norte,Pedro Soto,Laptop,Online,13,914.46,0.0,11887.98
115,1116,Febrero,Sur,Ana Torres,Monitor,Tienda fisica,14,360.65,0.0,5049.10
116,1117,Enero,Norte,Javier Munoz,Tablet,Online,10,313.44,0.0,3134.40
123,1124,Abril,Norte,Carlos Rivas,Laptop,Mayorista,12,849.20,0.0,10190.40
165,1166,Febrero,Sur,Ana Torres,Laptop,Tienda fisica,15,827.93,5.0,12418.95
207,1208,Abril,Sur,Roberto Fuentes,Laptop,NaN,15,977.16,20.0,14657.40
211,1212,Febrero,Norte,Roberto Fuentes,Tablet,Tienda fisica,15,303.75,0.0,4556.25
223,1224,Junio,Norte,Camila Vega,Laptop,Mayorista,13,1040.82,0.0,13530.66
225,1226,Mayo,Norte,Laura Diaz,Tablet,Online,14,389.30,10.0,5450.20
264,1265,Abril,Norte,Carlos Rivas,Monitor,Online,14,355.62,0.0,4978.68
266,1267,Marzo,Norte,Carlos Rivas,Laptop,Mayorista,13,778.38,15.0,10118.94
281,1282,Abril,Norte,Ana Torres,Tablet,Tienda fisica,14,355.95,15.0,4983.30
299,1300,Mayo,Sur,Javier Munoz,Tablet,Tienda fisica,10,353.19,20.0,3531.90

In [42]:
filtro5['region'].value_counts()

region
Norte    13
Sur       9
Name: count, dtype: int64

In [45]:
(df['cantidad'] >= 10)

0      False
1      False
2       True
3      False
4       True
       ...
295    False
296    False
297    False
298     True
299     True
Name: cantidad, Length: 300, dtype: bool

In [47]:
filtro6 = df[
    (df['region'].isin(['Norte', 'Sur'])) & 
    (df['monto_bruto'] >= df['monto_bruto'].mean())
]

In [48]:
filtro6['region'].value_counts()

region
Norte    17
Sur      13
Name: count, dtype: int64

In [49]:
def fV(df, region, categoria, monto_minimo):
    filtro = df[
        (df['region'] == region) &
        (df['categoria'] == categoria) &
        (df['monto_bruto'] >= monto_minimo)
    ]
    return filtro

In [50]:
r1 = fV(df, 'Norte', 'Tecnología', 5000)
print(r1)

r2 = fV(df, 'Sur', 'Hogar', 10000)
print(r2)

r3 = fV(df, 'Norte', 'Alimentos', 2000)
print(r3)

Empty DataFrame
Columns: [id_venta, mes, region, vendedor, categoria, canal, cantidad, precio_unit, descuento, monto_bruto]
Index: []
Empty DataFrame
Columns: [id_venta, mes, region, vendedor, categoria, canal, cantidad, precio_unit, descuento, monto_bruto]
Index: []
Empty DataFrame
Columns: [id_venta, mes, region, vendedor, categoria, canal, cantidad, precio_unit, descuento, monto_bruto]
Index: []

In [52]:
resumen = df.groupby('region').agg(
    suma_total=('monto_bruto', 'sum'),
    promedio=('monto_bruto', 'mean'),
    maximo=('monto_bruto', 'max'),
    minimo=('monto_bruto', 'min'),
    cantidad_transacciones=('monto_bruto', 'count')
).round(2)

resumen

        suma_total  promedio    maximo  minimo  cantidad_transacciones
region
Centro   110254.74   1934.29  13576.05   34.07                      57
Este     147358.93   2585.24  12010.88   69.24                      57
Norte    167154.38   2932.53  15186.30   33.77                      57
Oeste    183789.62   2588.59  14492.25   31.32                      71
Sur      120768.25   2082.21  14657.40   34.20                      58

In [53]:
resumen2 = resumen.reset_index().sort_values(
    by='suma_total', 
    ascending=False
)

resumen2

   region  suma_total  promedio    maximo  minimo  cantidad_transacciones
3   Oeste   183789.62   2588.59  14492.25   31.32                      71
2   Norte   167154.38   2932.53  15186.30   33.77                      57
1    Este   147358.93   2585.24  12010.88   69.24                      57
4     Sur   120768.25   2082.21  14657.40   34.20                      58
0  Centro   110254.74   1934.29  13576.05   34.07                      57

In [54]:
resumen_region_mes = df.groupby(['region', 'mes']).agg(
    suma_monto=('monto_bruto', 'sum'),
    suma_cantidad=('cantidad', 'sum')
).reset_index()

resumen_region_mes.head(10)

   region      mes  suma_monto  suma_cantidad
0  Centro    Abril    10390.50             64
1  Centro    Enero     8727.16             33
2  Centro  Febrero     6330.77             37
3  Centro    Junio    51903.36            120
4  Centro    Marzo    16884.87             81
5  Centro     Mayo    16018.08             62
6    Este    Abril    29469.73            111
7    Este    Enero    21131.64             64
8    Este  Febrero    25411.30             56
9    Este    Junio    25126.33             60

In [55]:
vendedor_top = df.groupby('vendedor')['monto_bruto'].sum().idxmax()

vendedor_top

'Camila Vega'

In [ ]:
# reset_index resetea el indice, si no lo pusiera las columnas agrupadas con grupby pasarian a ser indices
# se usa sum(), mean(), etc cuando necesitas hacer operaciones simplesy agg cuando quieres hacer varias operaciones